//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenBD_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderId { get; set; }
        public string OfferTitle { get; set; }
        public string OfferPercent { get; set; }
        public string OfferDescription { get; set; }
        public string ImageLink { get; set; }
        public string ProductLink { get; set; }
    }
}
