//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenBD_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int InvoiceNumber { get; set; }

        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public double Subtotal { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string ShippingAddress { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string DeliveryNumber { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string CardNumber { get; set; }
        public string CardType { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<InvoiceItem> InvoiceItems { get; set; }
        public User User { get; set; }
    }
}
