//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenBD_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;
    using ZenBD_API.Links;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Password { get; set; }
       
        public string UserType { get; set; }
        [JsonIgnore,XmlIgnore]
        public List<Link> links = new List<Link>();
        public List<Link> Links
        {
            get { return links; } 
        }

[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Invoice> Invoices { get; set; }
    }
}
