//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenBD_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfo
    {
        public int MessageId { get; set; }
        public string MessageName { get; set; }
        public string MessageEmail { get; set; }
        public string MessageText { get; set; }
    }
}
