//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenBD_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;
    using ZenBD_API.Links;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public double Price { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public int Quantity { get; set; }
        
        public string Image { get; set; }
        [Required(ErrorMessage = "Please enter a valid value")]
        public int CategoryId { get; set; }
    
        public Category Category { get; set; }


        [JsonIgnore, XmlIgnore]
        public List<Link> links = new List<Link>();
        public List<Link> Links
        {
            get { return links; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
